// react/src/components/molecules/ActionNavigation/index.tsx
"use client"

import { useContext } from "react";

import { ActionLinks } from "@/components/atoms";
import { SidebarContext } from "@/context/sidebar/context";
import { Cart } from "@/components/organisms";

const ActionNavigation = () => {
    const { open, setOpenState } = useContext(SidebarContext);

    return (
        <div className="relative flex items-center space-x-5 items-center">
            <Cart />
            <ActionLinks icon="FiUser" />
            <ActionLinks style="xl:hidden" icon="FiMenu" action={() => setOpenState(!open)} />
        </div>
    )
}

export default ActionNavigation;

// vue-nuxt/components/molecules/ActionNavigation.vue
<script setup lang="ts">
function handle () {
    console.log('handle action')
}
</script>

<template>
    <div class="relative flex items-center space-x-5 items-center">
        <atoms-action-links icon="bi:cart" @click="handle()" />
        <atoms-action-links icon="bi:person" @click="handle()" />
        <atoms-action-links icon="bi:list" class="xl:hidden" @click="handle()" />
    </div>
</template>
