// vue-nuxt/components/molecules/MenuNavigation.vue
<script setup lang="ts">
import useSharedData from "@/composables/useSharedData";
const { menu } = useSharedData();
</script>

<template>
    <nav class="hidden md:flex px-4 mx-auto">
        <ul class="flex font-semibold font-heading space-x-12">
            <li class="item" v-for="(item, index) in menu" :key="index">
                <atoms-nav-links v-bind="item" />
            </li>
        </ul>
    </nav>
</template>

// react/src/components/molecules/MenuNavigation/index.tsx
import { Key } from "react";
import { NavLinks } from "@/components/atoms";
import { MenuListPropsType } from "@/types/MenuList";
import { menuList } from "@/utils/menu";

const MenuNavigation = () => {
    return (
        <nav className="hidden md:flex px-4 mx-auto">
            <ul className="flex font-semibold font-heading space-x-12">
                {menuList.map((item: MenuListPropsType, key: Key) => <li key={key}><NavLinks {...item} /></li>)}
            </ul>
        </nav>
    )
}

export default MenuNavigation;
